### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by RafaelOliveira** [retrio/nes#7]
There are missing files, maybe you forgot to commit.

Assets.hx:303: [Assets] There is no Image asset with an ID of "graphics/upload.png"

**Comment by RafaelOliveira** [comment]
Same error in the gb emulator

**Comment by bendmorris** [comment]
Thanks, missed some assets. Please pull from retrio-core and try again.

**Comment by RafaelOliveira** [comment]
Now is working, thanks
